"""
Every number behind the directional-exposure work, in one reproducible
script: the opposite-direction gate (Anchor v1.0 -> v1.1) AND the
reversal exit (Anchor v1.1 -> v1.2), for both Anchor and Sentinel.

WHY THIS EXISTS AS A SCRIPT. The original 2026-08-27 numbers were
produced by ad-hoc inline one-liners, so when shadow.py's stale
forming-candle bug was found the next day (see _StructureCache's
docstring) there was nothing to just re-run -- the exact policy
combinations had to be reconstructed from log files. Everything the
published artifact claims is now regenerated by:

    python -m research.directional_exposure_backtest

Six policy runs over the full reconstructed NIFTY history:

    Anchor    v1.0  gate off, exit off      (the original frozen baseline)
    Anchor    v1.1  gate on,  exit off
    Anchor    v1.2  gate on,  exit on       (live)
    Sentinel  base  gate off, exit off      (v1.1-dev, 200pt/30min cluster cap)
    Sentinel  gate  gate on,  exit off      (declined on its own)
    Sentinel  full  gate on,  exit on       (v1.2-dev, live paper-tracking)

use_learned_adjustment=False throughout: it reads the LIVE journal, which
is a record of a recent period, so applying it to reconstructed history
from an earlier period is look-ahead bias. (It is also globally inert
right now -- config.LEARNED_TAG_ADJUSTMENT_ENABLED is off -- but passing
it explicitly keeps this honest if that flag is ever flipped back on.)
"""

import argparse
import json
from collections import defaultdict

import shadow
from research.concurrent_direction_exposure_study import CAPITAL, historical_days, run_policy_over_history
from research.one_trade_per_day_study import institutional_metrics, to_rows

ANCHOR_KWARGS = {"use_learned_adjustment": False}
SENTINEL_KWARGS = {
    "use_learned_adjustment": False,
    "strike_adjacency_band_points": 200,
    "cluster_window_minutes": 30,
}

# (label, use_opposite_direction_gate, use_reversal_exit)
STAGES = [
    ("baseline", False, False),
    ("gate_only", True, False),
    ("gate_plus_exit", True, True),
]


def annual_table(rows: list, capital: float) -> list:
    by_year = defaultdict(lambda: {"n": 0, "pnl": 0.0})
    for day, net, _r, _risk in rows:
        by_year[day[:4]]["n"] += 1
        by_year[day[:4]]["pnl"] += net
    out = []
    for y in sorted(by_year):
        v = by_year[y]
        out.append({"year": y, "n_trades": v["n"], "net_inr": round(v["pnl"], 0),
                    "return_pct": round(v["pnl"] / capital * 100, 2)})
    return out


def run_strategy(name: str, base_kwargs: dict, days: list) -> dict:
    out = {"label": name, "stages": {}}
    for stage, gate, exit_ in STAGES:
        print(f"  {name} / {stage} (gate={gate}, exit={exit_})...", flush=True)
        policy = shadow.Policy(name=f"{name}_{stage}", use_opposite_direction_gate=gate,
                               use_reversal_exit=exit_, **base_kwargs)
        trades = run_policy_over_history(policy, days)
        closed = [t for t in trades if t.outcome]
        rows = to_rows(closed)
        out["stages"][stage] = {
            "metrics": institutional_metrics(rows, capital=CAPITAL),
            "annual": annual_table(rows, CAPITAL),
            "n_reversal_exits": sum(1 for t in closed if t.outcome == "REVERSAL_EXIT"),
        }
    return out


def describe(results: list) -> str:
    keys = (("n", "{:.0f}"), ("win_rate_pct", "{:.1f}%"),
            ("total_return_pct", "{:+.1f}%"), ("max_dd_pct", "{:.1f}%"),
            ("calmar", "{:.2f}"), ("profit_factor", "{:.2f}"),
            ("expectancy_r", "{:+.4f}"), ("avg_trades_per_day", "{:.2f}"))
    lines = [f"Directional exposure controls (Rs{CAPITAL:,.0f} fixed capital base)", ""]
    for r in results:
        lines.append(f"-- {r['label']} --")
        lines.append(f"  {'metric':<22}{'baseline':>14}{'gate only':>14}{'gate + exit':>14}")
        for key, fmt in keys:
            cells = []
            for stage, _g, _e in STAGES:
                v = r["stages"][stage]["metrics"].get(key)
                cells.append(fmt.format(v) if v is not None else "n/a")
            lines.append(f"  {key:<22}" + "".join(f"{c:>14}" for c in cells))
        lines.append(f"  {'reversal exits':<22}" + "".join(
            f"{r['stages'][s]['n_reversal_exits']:>14}" for s, _g, _e in STAGES))
        lines.append("")
        lines.append(f"  {'year':<8}" + "".join(f"{s:>16}" for s, _g, _e in STAGES))
        years = sorted({row["year"] for s, _g, _e in STAGES for row in r["stages"][s]["annual"]})
        for y in years:
            cells = []
            for stage, _g, _e in STAGES:
                row = next((x for x in r["stages"][stage]["annual"] if x["year"] == y), None)
                cells.append(f"{row['return_pct']:+.1f}%" if row else "n/a")
            lines.append(f"  {y:<8}" + "".join(f"{c:>16}" for c in cells))
        lines.append("")
    return "\n".join(lines)


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--out", default="logs/directional_exposure_backtest.json")
    args = p.parse_args()

    days = historical_days()
    print(f"{len(days)} reconstructed NIFTY days\n", flush=True)

    results = [run_strategy("Anchor", ANCHOR_KWARGS, days),
               run_strategy("Sentinel", SENTINEL_KWARGS, days)]

    print()
    print(describe(results))
    with open(args.out, "w") as f:
        json.dump({"n_days": len(days), "capital": CAPITAL, "results": results}, f, indent=2)
    print(f"\nwritten to {args.out}")


if __name__ == "__main__":
    main()
